### ISSUE TITLE
该项目继续维护吗？？我最近也在做这种的项目

### ISSUE THREAD

**Issue by tianshaokai** [yangs2012/medicine#1]
1. 运行项目后发现闪退

**Comment by yangs2012** [comment]
维护中

**Comment by tianshaokai** [comment]
51. 点击判断题 填空题报错
2. 我们项目现在也有选择 填空，这种页面涉及app 60%页面，想封装一下 作者有什么好思路

**Comment by yangs2012** [comment]
啥错误啊
我这边没问题
填空那个用一个占位符代替空格，然后用textview的html格式显示，就可以显示不同的颜色了。

**Comment by tianshaokai** [comment]
不好意思 忘记贴图了
<img width="796" alt="qq20171020-220637 2x" src="https://user-images.githubusercontent.com/6706496/31825015-6904a6e6-b5e3-11e7-90c1-dbb40e442983.png">

**Comment by yangs2012** [comment]
这个错误是暂时  没修复  现在可以了

**Comment by tianshaokai** [comment]
这问题在我的手机里还是存在
